# Generated by Django 5.1.1 on 2024-09-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desctiption',
            new_name='description',
        ),
    ]
